version: '3'

services:
  web:
    build: .
    ports:
      - "50800:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
    networks:
      - webnet

  redis:
    image: "redis:alpine"
    networks:
      - webnet

  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
